osx_image: xcode7.1
language: objective-c
notifications:
  email: false
script:
  - xcodebuild test -project Reachability.xcodeproj -scheme Reachability -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
